// flow-typed signature: d98166446f03c36c7b65a66a600d853a
// flow-typed version: <<STUB>>/react-hammerjs_v^1.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hammerjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-hammerjs" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-hammerjs/dist/react-hammerjs.es" {
  declare module.exports: any;
}

declare module "react-hammerjs/dist/react-hammerjs" {
  declare module.exports: any;
}

declare module "react-hammerjs/dist/react-hammerjs.min" {
  declare module.exports: any;
}

declare module "react-hammerjs/gulpfile" {
  declare module.exports: any;
}

declare module "react-hammerjs/lib/Hammer" {
  declare module.exports: any;
}

declare module "react-hammerjs/rollup.config" {
  declare module.exports: any;
}

declare module "react-hammerjs/src/Hammer" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-hammerjs/dist/react-hammerjs.es.js" {
  declare module.exports: $Exports<"react-hammerjs/dist/react-hammerjs.es">;
}
declare module "react-hammerjs/dist/react-hammerjs.js" {
  declare module.exports: $Exports<"react-hammerjs/dist/react-hammerjs">;
}
declare module "react-hammerjs/dist/react-hammerjs.min.js" {
  declare module.exports: $Exports<"react-hammerjs/dist/react-hammerjs.min">;
}
declare module "react-hammerjs/gulpfile.js" {
  declare module.exports: $Exports<"react-hammerjs/gulpfile">;
}
declare module "react-hammerjs/lib/Hammer.js" {
  declare module.exports: $Exports<"react-hammerjs/lib/Hammer">;
}
declare module "react-hammerjs/rollup.config.js" {
  declare module.exports: $Exports<"react-hammerjs/rollup.config">;
}
declare module "react-hammerjs/src/Hammer.js" {
  declare module.exports: $Exports<"react-hammerjs/src/Hammer">;
}
